apiVersion: v1
kind: Service
metadata:
  name: {{ include "ccideas-mcp.fullname" . }}
  labels:
    {{- include "ccideas-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: echo
      protocol: TCP
      name: echo
  selector:
    {{- include "ccideas-mcp.selectorLabels" . | nindent 4 }}
